package gov.usgs.phast;

/*
 * JWizardPanel.java
 *
 * Created on July 19, 2002, 3:34 PM
 */

/**
 *
 * @author  charlton
 */
public class JWizardPanel extends javax.swing.JPanel {
    
    /** Creates new form JPanel1 */
    public JWizardPanel() {
        super();
        initComponents();
        pages = new java.util.Vector(1);
        currentPage = 0;
        jButtonBack.setEnabled(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanelMain = new javax.swing.JPanel();
        jPanelButtons = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelSubButtons = new javax.swing.JPanel();
        jPanelSubSubButtons = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonFinish = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelMain.setLayout(new java.awt.CardLayout());

        add(jPanelMain, java.awt.BorderLayout.CENTER);

        jPanelButtons.setLayout(new java.awt.BorderLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanelButtons.add(jSeparator1, java.awt.BorderLayout.NORTH);

        jPanelSubButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanelSubSubButtons.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        jButtonBack.setFont(new java.awt.Font("Dialog", 0, 11));
        jButtonBack.setMnemonic('B');
        jButtonBack.setText("< Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanelSubSubButtons.add(jButtonBack);

        jButtonNext.setFont(new java.awt.Font("Dialog", 0, 11));
        jButtonNext.setMnemonic('N');
        jButtonNext.setText("Next >");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jPanelSubSubButtons.add(jButtonNext);

        jButtonFinish.setFont(new java.awt.Font("Dialog", 0, 11));
        jButtonFinish.setMnemonic('F');
        jButtonFinish.setText("Finish");
        jButtonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishActionPerformed(evt);
            }
        });

        jPanelSubSubButtons.add(jButtonFinish);

        jButtonCancel.setFont(new java.awt.Font("Dialog", 0, 11));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanelSubSubButtons.add(jButtonCancel);

        jPanelSubButtons.add(jPanelSubSubButtons);

        jPanelButtons.add(jPanelSubButtons, java.awt.BorderLayout.CENTER);

        add(jPanelButtons, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

    private void jButtonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinishActionPerformed
        try {
            Object oldValue = pages.get(currentPage);
            Object newValue = pages.get(pages.size() - 1);
            
            if (oldValue.equals(newValue)) {
                newValue = null;
            }
            else {
                fireVetoableChange(PAGE_CHANGING_PROPERTY, oldValue, newValue);
                
                java.awt.CardLayout layout = (java.awt.CardLayout)jPanelMain.getLayout();
                currentPage = pages.size() - 1;
                layout.show(jPanelMain, Integer.toString(currentPage));
                setEnabledBack(currentPage > 0);
                setEnabledNext(currentPage < pages.size() - 1);                
            }            
            fireVetoableChange(FINISH_PRESSED_PROPERTY, oldValue, newValue);
            
            java.awt.CardLayout layout = (java.awt.CardLayout)jPanelMain.getLayout();
            currentPage = pages.size() - 1;
            layout.show(jPanelMain, Integer.toString(currentPage));
            setEnabledBack(currentPage > 0);
            setEnabledNext(currentPage < pages.size() - 1);            
        }
        catch (java.beans.PropertyVetoException e) {}        
    }//GEN-LAST:event_jButtonFinishActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        try {
            Object oldValue = pages.get(currentPage);
            Object newValue = pages.get(currentPage - 1);

            fireVetoableChange(PAGE_CHANGING_PROPERTY, oldValue, newValue);
            
            java.awt.CardLayout layout = (java.awt.CardLayout)jPanelMain.getLayout();
            --currentPage;
            layout.show(jPanelMain, Integer.toString(currentPage));            
            setEnabledBack(currentPage > 0);
            setEnabledNext(currentPage < pages.size() - 1);
        }
        catch (java.beans.PropertyVetoException e) {}
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // Add your handling code here:
        try {
            Object oldValue = pages.get(currentPage);
            Object newValue = pages.get(currentPage + 1);

            fireVetoableChange(PAGE_CHANGING_PROPERTY, oldValue, newValue);
            
            java.awt.CardLayout layout = (java.awt.CardLayout)jPanelMain.getLayout();
            ++currentPage;
            layout.show(jPanelMain, Integer.toString(currentPage));
            setEnabledBack(true);
            setEnabledNext(currentPage < pages.size() - 1);
        }
        catch (java.beans.PropertyVetoException e) {}
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    public javax.swing.JPanel getMainPanel() {
        return jPanelMain;
    }    
    
    public void addComponent(java.awt.Component component) {
        int index = pages.size();
        pages.add(component);
        jPanelMain.add(component, Integer.toString(index));
    }    
    
    public void setEnabledBack(boolean b) {
        jButtonBack.setEnabled(b);
    }
    public void setEnabledNext(boolean b) {
        jButtonNext.setEnabled(b);
    }
    public void setEnabledFinish(boolean b) {
        jButtonFinish.setEnabled(b);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelSubButtons;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jButtonFinish;
    private javax.swing.JPanel jPanelSubSubButtons;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonBack;
    // End of variables declaration//GEN-END:variables

    private java.util.Vector   pages;
    private int                currentPage;
    
    public static final String NEXT_PRESSED_PROPERTY   = "next";
    public static final String BACK_PRESSED_PROPERTY   = "back";
    public static final String FINISH_PRESSED_PROPERTY = "finish";
    public static final String PAGE_CHANGING_PROPERTY  = "page_changing";
    
}
