#!/bin/sh
if [ $USER == dlpark ]; then
    PHASTDIR=/z/parkplace/home/dlpark/programs/phastpp
fi
if [ $USER == charlton ]; then
    PHASTDIR=/z/srv2rcolkr/home/charlton/programs/phastpp
fi
EXDIR=$PHASTDIR/examples
CONFIGURATION=OPENMPI
#
#   make directory
#
NAME=$1
cd $NAME
mkdir -p 0
rm -f 0/*
#
#   distribute files
#
if [ -f $NAME.trans.dat ]; then 
    cp $NAME.trans.dat 0
    fi
if [ -f $NAME.chem.dat ]; then 
    cp $NAME.chem.dat 0
    fi
if [ -f $NAME.head.dat ]; then 
    cp $NAME.head.dat 0
    fi
if [ $NAME == "ex4restart" ]; then 
    cp ex4.head.dat 0
    cp ex4.restart.gz 0
    fi
if [ $NAME == "print_check_transient" ]; then 
    cp print_check_ss.head.dat 0
    fi
if [ $NAME == "property" ]; then 
    cp property.solns property.mix property.mix.xyzt property.xyzt 0
    fi
if [ $NAME == "ex4_transient" ]; then 
    cp ex4.head.dat 0
    fi
if [ -f phast.dat ]; then 
    cp phast.dat 0
    fi
if [ $CONFIGURATION == "LAM" ]; then
    cp ../schema 0
    cd 0
    sed -e "s?WORKING_DIRECTORY?$EXDIR/$NAME/0?" \
	-e "s^EXECUTABLE^$PHASTDIR/src/phast/mpi_lahey/phast^" schema > temp; mv temp schema
#
#   run phastinput
#
    $PHASTDIR/src/phastinput/phastinput $NAME
    echo Done phastinput.
#
#   run phast
#
    lamboot ../../hosts;  time mpirun-lam -O -v schema; wipe ../../hosts
else 
    if [ $CONFIGURATION == "OPENMPI" ]; then
	cd 0
#
#   run phastinput
#
	TMP=/z/parkplace/home/dlpark/tmp
	TMPDIR=/z/parkplace/home/dlpark/tmp
	$PHASTDIR/src/phastinput/phastinput $NAME
	echo Done phastinput.
#
#   run phast
#
	mpirun -n 4 -hostfile ../../hosts_openmpi -v -wdir $EXDIR/$NAME/0 $PHASTDIR/src/phast/openmpi_gfortran/phast
    fi
fi
