/*
 * JPage1.java
 *
 * Created on July 24, 2002, 3:42 PM
 */

package gov.usgs.phast;

/**
 *
 * @author  charlton
 */
public class JPage2 extends javax.swing.JPanel implements java.beans.VetoableChangeListener {
    
    /** Creates new form JPage1 */
    public JPage2() {
        initComponents();
        
        xTab = new JPage2Tab();
        jTabbedPane.addTab("X-Coor", xTab);
        
        yTab = new JPage2Tab();
        jTabbedPane.addTab("Y-Coor", yTab);
        
        zTab = new JPage2Tab();
        jTabbedPane.addTab("Z-Coor", zTab);
        
        timesTab = new JPage2Tab();
        jTabbedPane.addTab("Times", timesTab);
        
        scalarsTab = new JPage2Tab();
        jTabbedPane.addTab("Scalars", scalarsTab);
        
        vectorsTab = new JPage2Tab();
        jTabbedPane.addTab("Vectors", vectorsTab);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTabbedPane.setFont(new java.awt.Font("Dialog", 0, 12));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jTabbedPane, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    public void vetoableChange(java.beans.PropertyChangeEvent propertyChangeEvent) throws java.beans.PropertyVetoException {
        if (propertyChangeEvent.getSource() instanceof JWizardPanel) {
            if (propertyChangeEvent.getPropertyName().equals(JWizardPanel.PAGE_CHANGING_PROPERTY)) {
                if (propertyChangeEvent.getOldValue().equals(this)) {
                }
            }
        }
    }
    
    public void setPhastH5File(gov.usgs.phast.PhastH5File hdf) {        
        xTab.setListData(hdf.getX());
        yTab.setListData(hdf.getY());
        zTab.setListData(hdf.getZ());
        timesTab.setListData(hdf.getTimeSteps());
        scalarsTab.setListData(hdf.getScalars());
        vectorsTab.setListData(hdf.getVectors());
    }    
    
    public boolean[] getSelectedX() {
        return xTab.getSelected();
    }
    public boolean[] getSelectedY() {
        return yTab.getSelected();
    }
    public boolean[] getSelectedZ() {
        return zTab.getSelected();
    }
    public boolean[] getSelectedTimes() {
        return timesTab.getSelected();
    }
    public boolean[] getSelectedScalars() {
        return scalarsTab.getSelected();
    }
    public boolean[] getSelectedVectors() {
        return vectorsTab.getSelected();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
    private JPage2Tab xTab;
    private JPage2Tab yTab;
    private JPage2Tab zTab;
    private JPage2Tab timesTab;
    private JPage2Tab scalarsTab;
    private JPage2Tab vectorsTab;

}
