sed -i -e "s/RM_Abort/rm_abort/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_Abort/rm_abort/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_CloseFiles/rm_closefiles/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_Concentrations2Utility/rm_concentrations2utility/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_CreateMapping/rm_createmapping/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_Create/rm_create/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_DecodeError/rm_decodeerror/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_Destroy/rm_destroy/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_DumpModule/rm_dumpmodule/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_ErrorMessage/rm_errormessage/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_FindComponents/rm_findcomponents/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetChemistryCellCount/rm_getchemistrycellcount/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetComponentCount/rm_getcomponentcount/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetComponent/rm_getcomponent/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetConcentrations/rm_getconcentrations/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetDensity/rm_getdensity/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetErrorString/rm_geterrorstring/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetErrorStringLength/rm_geterrorstringlength/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetFilePrefix/rm_getfileprefix/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetGfw/rm_getgfw/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetGridCellCount/rm_getgridcellcount/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetIPhreeqcId/rm_getiphreeqcid/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetMpiMyself/rm_getmpimyself/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetMpiTasks/rm_getmpitasks/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetNthSelectedOutputUserNumber/rm_getnthselectedoutputusernumber/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSaturation/rm_getsaturation/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSelectedOutputColumnCount/rm_getselectedoutputcolumncount/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSelectedOutputCount/rm_getselectedoutputcount/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSelectedOutputHeading/rm_getselectedoutputheading/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSelectedOutputRowCount/rm_getselectedoutputrowcount/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSelectedOutput/rm_getselectedoutput/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSolutionVolume/rm_getsolutionvolume/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSpeciesConcentrations/rm_getspeciesconcentrations/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSpeciesCount/rm_getspeciescount/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSpeciesD25/rm_getspeciesd25/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSpeciesName/rm_getspeciesname/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSpeciesSaveOn/rm_getspeciessaveon/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetSpeciesZ/rm_getspeciesz/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetThreadCount/rm_getthreadcount/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetTimeConversion/rm_gettimeconversion/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetTimeStep/rm_gettimestep/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_GetTime/rm_gettime/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_InitialPhreeqc2Concentrations/rm_initialphreeqc2concentrations/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_InitialPhreeqc2Module/rm_initialphreeqc2module/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_InitialPhreeqcCell2Module/rm_initialphreeqccell2module/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_InitialPhreeqc2SpeciesConcentrations/rm_initialphreeqc2speciesconcentrations/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_LoadDatabase/rm_loaddatabase/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_LogMessage/rm_logmessage/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_MpiWorkerBreak/rm_mpiworkerbreak/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_MpiWorker/rm_mpiworker/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_OpenFiles/rm_openfiles/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_OutputMessage/rm_outputmessage/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_RunCells/rm_runcells/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_RunFile/rm_runfile/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_RunString/rm_runstring/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_ScreenMessage/rm_screenmessage/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetComponentH2O/rm_setcomponenth2o/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetConcentrations/rm_setconcentrations/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetCurrentSelectedOutputUserNumber/rm_setcurrentselectedoutputusernumber/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetDensity/rm_setdensity/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetDumpFileName/rm_setdumpfilename/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetErrorHandlerMode/rm_seterrorhandlermode/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetFilePrefix/rm_setfileprefix/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetMpiWorkerCallback/rm_setmpiworkercallback/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetPartitionUZSolids/rm_setpartitionuzsolids/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetPorosity/rm_setporosity/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetPrintChemistryMask/rm_setprintchemistrymask/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetPrintChemistryOn/rm_setprintchemistryon/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetPressure/rm_setpressure/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetRebalanceFraction/rm_setrebalancefraction/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetRebalanceByCell/rm_setrebalancebycell/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetRepresentativeVolume/rm_setrepresentativevolume/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetSaturation/rm_setsaturation/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetSelectedOutputOn/rm_setselectedoutputon/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetSpeciesSaveOn/rm_setspeciessaveon/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetTemperature/rm_settemperature/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetTimeConversion/rm_settimeconversion/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetTimeStep/rm_settimestep/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetTime/rm_settime/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetUnitsExchange/rm_setunitsexchange/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetUnitsGasPhase/rm_setunitsgasphase/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetUnitsKinetics/rm_setunitskinetics/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetUnitsPPassemblage/rm_setunitsppassemblage/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetUnitsSolution/rm_setunitssolution/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetUnitsSSassemblage/rm_setunitsssassemblage/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetUnitsSSassemblage/rm_setunitsssassemblage/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SetUnitsSurface/rm_setunitssurface/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_SpeciesConcentrations2Module/rm_speciesconcentrations2module/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_UseSolutionDensityVolume/rm_usesolutiondensityvolume/g" ..\PhreeqcRM\RM_interface.F90
sed -i -e "s/RM_WarningMessage/rm_warningmessage/g" ..\PhreeqcRM\RM_interface.F90