sed -i "s///g" .\html\classphreeqcrm.html 
sed -i "s/rm_abort/RM_Abort/g" .\html\classphreeqcrm.html 
sed -i "s/rm_closefiles/RM_CloseFiles/g" .\html\classphreeqcrm.html 
sed -i "s/rm_concentrations2utility/RM_Concentrations2Utility/g" .\html\classphreeqcrm.html 
sed -i "s/rm_create/RM_Create/g" .\html\classphreeqcrm.html 
sed -i "s/rm_createmapping/RM_CreateMapping/g" .\html\classphreeqcrm.html 
sed -i "s/rm_decodeerror/RM_DecodeError/g" .\html\classphreeqcrm.html 
sed -i "s/rm_destroy/RM_Destroy/g" .\html\classphreeqcrm.html 
sed -i "s/rm_dumpmodule/RM_DumpModule/g" .\html\classphreeqcrm.html 
sed -i "s/rm_errormessage/RM_ErrorMessage/g" .\html\classphreeqcrm.html 
sed -i "s/rm_findcomponents/RM_FindComponents/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getchemistrycellcount/RM_GetChemistryCellCount/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getcomponent/RM_GetComponent/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getcomponentcount/RM_GetComponentCount/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getconcentrations/RM_GetConcentrations/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getdensity/RM_GetDensity/g" .\html\classphreeqcrm.html 
sed -i "s/rm_geterrorstring/RM_GetErrorString/g" .\html\classphreeqcrm.html 
sed -i "s/rm_geterrorstringlength/RM_GetErrorStringLength/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getfileprefix/RM_GetFilePrefix/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getgfw/RM_GetGfw/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getgridcellcount/RM_GetGridCellCount/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getiphreeqcid/RM_GetIPhreeqcId/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getmpimyself/RM_GetMpiMyself/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getmpitasks/RM_GetMpiTasks/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getnthselectedoutputusernumber/RM_GetNthSelectedOutputUserNumber/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getsaturation/RM_GetSaturation/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getselectedoutput/RM_GetSelectedOutput/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getselectedoutputcolumncount/RM_GetSelectedOutputColumnCount/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getselectedoutputcount/RM_GetSelectedOutputCount/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getselectedoutputheading/RM_GetSelectedOutputHeading/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getselectedoutputrowcount/RM_GetSelectedOutputRowCount/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getsolutionvolume/RM_GetSolutionVolume/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getspeciesconcentrations/RM_GetSpeciesConcentrations/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getspeciescount/RM_GetSpeciesCount/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getspeciesd25/RM_GetSpeciesD25/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getspeciesname/RM_GetSpeciesName/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getspeciessaveon/RM_GetSpeciesSaveOn/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getspeciesz/RM_GetSpeciesZ/g" .\html\classphreeqcrm.html 
sed -i "s/rm_getthreadcount/RM_GetThreadCount/g" .\html\classphreeqcrm.html 
sed -i "s/rm_gettime/RM_GetTime/g" .\html\classphreeqcrm.html 
sed -i "s/rm_gettimeconversion/RM_GetTimeConversion/g" .\html\classphreeqcrm.html 
sed -i "s/rm_gettimestep/RM_GetTimeStep/g" .\html\classphreeqcrm.html 
sed -i "s/rm_initialphreeqc2concentrations/RM_InitialPhreeqc2Concentrations/g" .\html\classphreeqcrm.html 
sed -i "s/rm_initialphreeqc2module/RM_InitialPhreeqc2Module/g" .\html\classphreeqcrm.html 
sed -i "s/rm_initialphreeqccell2module/RM_InitialPhreeqcCell2Module/g" .\html\classphreeqcrm.html 
sed -i "s/rm_initialphreeqc2speciesconcentrations/RM_InitialPhreeqc2SpeciesConcentrations/g" .\html\classphreeqcrm.html 
sed -i "s/rm_loaddatabase/RM_LoadDatabase/g" .\html\classphreeqcrm.html 
sed -i "s/rm_logmessage/RM_LogMessage/g" .\html\classphreeqcrm.html 
sed -i "s/rm_mpiworker/RM_MpiWorker/g" .\html\classphreeqcrm.html 
sed -i "s/rm_mpiworkerbreak/RM_MpiWorkerBreak/g" .\html\classphreeqcrm.html 
sed -i "s/rm_openfiles/RM_OpenFiles/g" .\html\classphreeqcrm.html 
sed -i "s/rm_outputmessage/RM_OutputMessage/g" .\html\classphreeqcrm.html 
sed -i "s/rm_runcells/RM_RunCells/g" .\html\classphreeqcrm.html 
sed -i "s/rm_runfile/RM_RunFile/g" .\html\classphreeqcrm.html 
sed -i "s/rm_runstring/RM_RunString/g" .\html\classphreeqcrm.html 
sed -i "s/rm_screenmessage/RM_ScreenMessage/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setcomponenth2o/RM_SetComponentH2O/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setconcentrations/RM_SetConcentrations/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setcurrentselectedoutputusernumber/RM_SetCurrentSelectedOutputUserNumber/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setdensity/RM_SetDensity/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setdumpfilename/RM_SetDumpFileName/g" .\html\classphreeqcrm.html 
sed -i "s/rm_seterrorhandlermode/RM_SetErrorHandlerMode/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setfileprefix/RM_SetFilePrefix/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setmpiworkercallback/RM_SetMpiWorkerCallback/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setpartitionuzsolids/RM_SetPartitionUZSolids/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setporosity/RM_SetPorosity/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setprintchemistrymask/RM_SetPrintChemistryMask/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setprintchemistryon/RM_SetPrintChemistryOn/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setpressure/RM_SetPressure/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setrebalancefraction/RM_SetRebalanceFraction/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setrebalancebycell/RM_SetRebalanceByCell/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setrepresentativevolume/RM_SetRepresentativeVolume/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setsaturation/RM_SetSaturation/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setselectedoutputon/RM_SetSelectedOutputOn/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setspeciessaveon/RM_SetSpeciesSaveOn/g" .\html\classphreeqcrm.html 
sed -i "s/rm_settemperature/RM_SetTemperature/g" .\html\classphreeqcrm.html 
sed -i "s/rm_settime/RM_SetTime/g" .\html\classphreeqcrm.html 
sed -i "s/rm_settimeconversion/RM_SetTimeConversion/g" .\html\classphreeqcrm.html 
sed -i "s/rm_settimestep/RM_SetTimeStep/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setunitsexchange/RM_SetUnitsExchange/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setunitsgasphase/RM_SetUnitsGasPhase/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setunitskinetics/RM_SetUnitsKinetics/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setunitsppassemblage/RM_SetUnitsPPassemblage/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setunitssolution/RM_SetUnitsSolution/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setunitsssassemblage/RM_SetUnitsSSassemblage/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setunitsssassemblage/RM_SetUnitsSSassemblage/g" .\html\classphreeqcrm.html 
sed -i "s/rm_setunitssurface/RM_SetUnitsSurface/g" .\html\classphreeqcrm.html 
sed -i "s/rm_speciesconcentrations2module/RM_SpeciesConcentrations2Module/g" .\html\classphreeqcrm.html 
sed -i "s/rm_usesolutiondensityvolume/RM_UseSolutionDensityVolume/g" .\html\classphreeqcrm.html 
sed -i "s/rm_warningmessage/RM_WarningMessage/g" .\html\classphreeqcrm.html 