/* config.h.  Generated by configure.  */
#if defined(_WIN32) || defined(_WIN64)
#define isnan _isnan
#define strdup _strdup
#define copysign _copysign
#if (_MSC_VER < 1900)
#define rint (int)
#endif
#define M_PI 3.14159265358979323846
#define TRILIBRARY
#define NO_TIMER
#endif
#if defined(__GNUC__) || defined(__SUNPRO_CC)
#define _hypot hypot
#endif
//#define sscanf sscanf_s
//#define strcpy strcpy_s
//#define strcat strcat_s
//#define strerror strerror_s
//#define fopen fopen_s
//#define strtok strtok_s
