/* config.h.  Generated by configure.  */
#if defined(_WIN32)
#define isnan _isnan
#define strdup _strdup
#define copysign _copysign
#define rint (int)
#define M_PI 3.14159265358979323846
#define TRILIBRARY
#define NO_TIMER
#endif
#if defined(__GNUC__)
#define _hypot hypot
#endif
//#define sscanf sscanf_s
//#define strcpy strcpy_s
//#define strcat strcat_s
//#define strerror strerror_s
//#define fopen fopen_s
//#define strtok strtok_s
