#!/bin/sh
if [ $USER == dlpark ]; then
    #PHASTDIR=/lobo02home/dlpark/programs/phastpp3-worker
    PHASTDIR=/home/charlton/reactive-transport/phastpp3-worker
fi
if [ $USER == charlton ]; then
    ##PHASTDIR=/z/srv2rcolkr/home/charlton/programs/phastpp
    PHASTDIR=/home/charlton/reactive-transport/phastpp3-worker
fi
EXDIR=$PHASTDIR/examples
###TMP=/lobo02home/dlpark/temp
###TMPDIR=/lobo02home/dlpark/temp
# 32 Bit Parallel versions
#CONFIGURATION=LAM_LAHEY
#CONFIGURATION=LAM_LAHEY_DEBUG
#CONFIGURATION=LAM_GFORTRAN
#CONFIGURATION=LAM_INTEL
#CONFIGURATION=LAM_INTEL_DEBUG
#CONFIGURATION=OPENMPI_GFORTRAN
#CONFIGURATION=OPENMPI_INTEL
# 64-Bit Parallel versions
CONFIGURATION=OPENMPI_GFORTRAN_64
#CONFIGURATION=OPENMPI_INTEL_64
#CONFIGURATION=OPENMPI_INTEL_64_DEBUG
#
#   make directory
#
NAME=$1
cd $NAME
mkdir -p 0
rm -f 0/*
#
#   distribute files
#
if [ -f $NAME.trans.dat ]; then 
    cp $NAME.trans.dat 0
    fi
if [ -f $NAME.chem.dat ]; then 
    cp $NAME.chem.dat 0
    fi
if [ -f $NAME.head.dat ]; then 
    cp $NAME.head.dat 0
    fi
if [ $NAME == "ex4restart" ]; then 
    cp ex4.head.dat 0
    cp ex4.restart.gz 0
    fi
if [ $NAME == "print_check_transient" ]; then 
    cp print_check_ss.head.dat 0
    fi
if [ $NAME == "property" ]; then 
    cp property.solns property.mix property.mix.xyzt property.xyzt 0
    fi
if [ $NAME == "ex4_transient" ]; then 
    cp ex4.head.dat 0
    fi
if [ -f phast.dat ]; then 
    cp phast.dat 0
    fi

#
#   run phastinput
#
$PHASTDIR/src/phastinput/phastinput $NAME
cd 0
cp ../Phast.tmp .
cp ../$NAME.log.txt .
echo Done phastinput.

if [ $CONFIGURATION == "LAM_LAHEY" ]; then
# 
#   32 bit lam_lahey
#
    cp ../../schema .
    sed -e "s?WORKING_DIRECTORY?$EXDIR/$NAME/0?" \
	-e "s^EXECUTABLE^$PHASTDIR/src/phast/lam_lahey/phast^" schema > temp; mv temp schema
#
#   run phast
#
    lamboot ../../hosts;  time mpirun-lam -O -v schema; wipe ../../hosts
fi

if [ $CONFIGURATION == "LAM_LAHEY_DEBUG" ]; then
# 
#   32 bit lam_lahey_debug
#
    cp ../../schema .
    sed -e "s?WORKING_DIRECTORY?$EXDIR/$NAME/0?" \
	-e "s^EXECUTABLE^$PHASTDIR/para_trans_chem/src/phast/lam_lahey_debug/phast^" schema > temp; mv temp schema
#
#   run phast
#
    lamboot ../../hosts;  time mpirun-lam -O -v schema; wipe ../../hosts
fi

if [ $CONFIGURATION == "LAM_GFORTRAN" ]; then
# 
#   32 bit lam_gfortran
#
    cp ../../schema .
    sed -e "s?WORKING_DIRECTORY?$EXDIR/$NAME/0?" \
	-e "s^EXECUTABLE^$PHASTDIR/src/phast/lam_gfortran/phast^" schema > temp; mv temp schema
#
#   run phast
#
    lamboot ../../hosts;  time mpirun-lam -O -v schema; wipe ../../hosts
fi

if [ $CONFIGURATION == "LAM_INTEL" ]; then
# 
#   32 bit lam_intel
#
    cp ../../schema .
    sed -e "s?WORKING_DIRECTORY?$EXDIR/$NAME/0?" \
	-e "s^EXECUTABLE^$PHASTDIR/src/phast/lam_intel/phast^" schema > temp; mv temp schema
#
#   run phast
#
    lamboot ../../hosts;  time mpirun-lam -O -v schema; wipe ../../hosts
fi

if [ $CONFIGURATION == "LAM_INTEL_DEBUG" ]; then
# 
#   32 bit lam_intel_debug
#
    cp ../../schema .
    sed -e "s?WORKING_DIRECTORY?$EXDIR/$NAME/0?" \
	-e "s^EXECUTABLE^$PHASTDIR/src/phast/lam_intel_debug/phast^" schema > temp; mv temp schema
#
#   run phast
#
    lamboot ../../hosts;  time mpirun-lam -O -v schema; wipe ../../hosts
fi

if [ $CONFIGURATION == "OPENMPI_GFORTRAN" ]; then
# 
#   32 bit openmpi_gfortran
#
    /z/parkplace/home/charlton/openmpi-1.4.2/grundvand-gfortran/bin/mpirun -n 2 -H grundvand -H niwot -v -wdir $EXDIR/$NAME/0 $PHASTDIR/src/phast/openmpi_gfortran/phast
fi

if [ $CONFIGURATION == "OPENMPI_INTEL" ]; then
# 
#   32 bit openmpi_intel
#
    #LD_LIBRARY_PATH=/z/parkplace/home/charlton/openmpi-1.4.2/grundvand-ifort/lib
    #export LD_LIBRARY_PATH
    /z/parkplace/home/charlton/openmpi-1.4.2/grundvand-ifort/bin/mpirun -n 2 -H parkplace -v -wdir $EXDIR/$NAME/0 $PHASTDIR/src/phast/openmpi_intel/phast
fi

if [ $CONFIGURATION == "OPENMPI_INTEL_64" ]; then
# 
#   64 bit openmpi_intel_64
#
#    /z/parkplace/home/charlton/openmpi-1.4.2/robocomp-ifort-x64/bin/mpirun  -n 2 -H robocomp -H lobo -v -wdir $EXDIR/$NAME/0 $PHASTDIR/src/phast/openmpi_intel_64/phast
    /usr/lib64/openmpi/bin/mpiexec  -n 8 -H lobo02 -v -wdir $EXDIR/$NAME/0 $PHASTDIR/src/phast/openmpi_intel_64/phast
fi

if [ $CONFIGURATION == "OPENMPI_INTEL_64_DEBUG" ]; then
# 
#   64 bit openmpi_intel_64_debug
#
#    /z/parkplace/home/charlton/openmpi-1.4.2/robocomp-ifort-x64/bin/mpirun  -n 4 -H robocomp -H lobo -v -wdir $EXDIR/$NAME/0 $PHASTDIR/src/phast/openmpi_intel_64_debug/phast
#    /z/parkplace/home/charlton/openmpi-1.4.2/robocomp-ifort-x64/bin/mpirun  -n 4 -H lobo -v -wdir $EXDIR/$NAME/0 $PHASTDIR/src/phast/openmpi_intel_64_debug/phast
    /z/parkplace/home/charlton/openmpi-1.4.2/robocomp-ifort-x64/bin/mpirun  -n 12 -H grundvand -H robocomp -H lobo -v -wdir $EXDIR/$NAME/0 $PHASTDIR/para_trans_chem/src/phast/openmpi_intel_64_debug/phast
fi

if [ $CONFIGURATION == "OPENMPI_GFORTRAN_64" ]; then
# 
#   64 bit openmpi_gfortran_64
#
    ##/usr/lib64/openmpi/bin/mpirun -n 8 -H arc1 -v -wdir $EXDIR/$NAME/0 $PHASTDIR/src/phast/openmpi_gfortran_64/phast
    /usr/lib64/openmpi/bin/mpirun -n 8 -v -wdir $EXDIR/$NAME/0 $PHASTDIR/src/phast/openmpi_gfortran_64/phast
fi

