#!/bin/sh
#
#   make directory
#
NAME=$1
cd $NAME
mkdir -p 0
rm -f 0/*
#
#  Set names
#
PHASTDIR=/cygdrive/c/Programs/phastpp
#mpiexec -n 4 -localonly C:/Programs/phastpp/src/phast/win32_2005/x64/merge/phast.exe
#PHAST_MPICH='c:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE\devenv.exe'

# My 32 bit release
#PHAST_INPUT=/cygdrive/c/Programs/phastpp/src/phastinput/vc80/Release/phastinput.exe
#PHAST_MPICH=c:\\Programs\\phastpp\\src\\phast\\win32_2005\\merge\\phast.exe

# 32 bit release
#PHAST_INPUT=C:/Program\ Files\ \(x86\)/USGS\phast-2.0.4799/bin/phastinput.exe
#PHAST_MPICH=C:/Program\ Files\ \(x86\)/USGS\phast-2.0.4799/bin/phast-mpich2.exe

# My 64 bit release
#PHAST_INPUT=/cygdrive/c/Programs/phastpp/src/phastinput/vc80/x64/Release/phastinput.exe
#PHAST_MPICH=c:/Programs/phastpp/src/phast/win32_2005/x64/merge/phast.exe

# 64 bit release
PHAST_INPUT=C:/Program\ Files/USGS/phast-2.0.4799/bin/phastinput.exe
PHAST_MPICH=C:/Program\ Files/USGS/phast-2.0.4799/bin/phast-mpich2.exe

# 32 bit debug
#PHAST_INPUT=/cygdrive/c/Programs/phastpp/src/phastinput/vc80/Debug/phastinput.exe
#PHAST_MPICH=c:/Programs/phastpp/src/phast/win32_2005/merge_debug/phast.exe

# 64 bit debug
#PHAST_INPUT=/cygdrive/c/Programs/phastpp/src/phastinput/vc80/x64/Debug/phastinput.exe
#PHAST_MPICH=c:/Programs/phastpp/src/phast/win32_2005/x64/merge_debug/phast.exe

#EXDIR=$PHASTDIR/examples
EXDIR=c:\\Programs\\phastpp\\examples
MPICHRUN=/cygdrive/c/Program\ Files/MPICH2/bin/mpiexec
#
#   distribute files
#
if [ -f $NAME.trans.dat ]; then 
    cp $NAME.trans.dat 0
    fi
if [ -f $NAME.chem.dat ]; then 
    cp $NAME.chem.dat 0
    fi
if [ -f $NAME.head.dat ]; then 
    cp $NAME.head.dat 0
    fi
if [ $NAME = 'ex4restart' ]; then 
    cp ex4.head.dat 0
    cp ex4.restart.gz 0
    fi
if [ $NAME = "print_check_transient" ]; then 
    cp print_check_ss.head.dat 0
    fi
if [ $NAME == "property" ]; then 
    cp property.solns property.mix property.mix.xyzt property.xyzt 0
    fi
if [ $NAME = "ex4_transient" ]; then 
    cp ex4.head.dat 0
    fi    
if [ -f phast.dat ]; then 
    cp phast.dat 0
    fi
##cp ../schema 0
cd 0
#
#   run phastinput
#
echo "$PHAST_INPUT" $NAME
"$PHAST_INPUT" $NAME
echo Done phastinput.
#
#   run phast_mpich
#
echo "$MPICHRUN" -np 7 -localonly -wdir $EXDIR\\$NAME\\0 $PHAST_MPICH
time "$MPICHRUN" -np 7 -localonly -wdir $EXDIR\\$NAME\\0 "$PHAST_MPICH"
