#include "PHRQ_type.h"
int add_elt_list(struct elt_list *elt_list_ptr, LDBLE coef);
int backspace_screen(int spaces);
LDBLE calc_alk(struct reaction *rxn_ptr);
int compute_gfw(const char *string, LDBLE * gfw);
int copy_token(char *token_ptr, char **ptr, int *length);
int dup_print(const char *ptr, int emphasis);
int equal(LDBLE a, LDBLE b, LDBLE eps);
void *free_check_null(void *ptr);
//void free_hash_strings(HashTable * Table);
int get_token(char **eqnaddr, char *string, LDBLE * z, int *l);
//int hcreate_multi(unsigned Count, HashTable ** HashTable_ptr);
//void hdestroy_multi(HashTable * HashTable_ptr);
//ENTRY *hsearch_multi(HashTable * Table, ENTRY item, ACTION action);
int islegit(const char c);
void malloc_error(void);
int parse_couple(char *token);
int print_centered(const char *string);
int replace(const char *str1, const char *str2, char *str);
void space(void **ptr, int i, int *max, int struct_size);
void squeeze_white(char *s_l);
int status(int count, const char *str);
void str_tolower(char *str);
void str_toupper(char *str);
//CLASS_STATIC int strcmp_nocase(const char *str1, const char *str2);
int strcmp_nocase(const char *str1, const char *str2);
int strcmp_nocase_arg1(const char *str1, const char *str2);
char *string_duplicate(const char *token);
char *string_hsave(const char *str);
char *string_pad(char *str, int i);
int string_trim(char *str);
int string_trim_right(char *str);
int string_trim_left(char *str);
//CLASS_STATIC LDBLE under(LDBLE xval);
LDBLE under(LDBLE xval);
void zero_double(LDBLE * target, int n);