    !MS$ ATTRIBUTES Default :: MPI_ADDRESS
    !MS$ ATTRIBUTES Default :: MPI_BARRIER
    !MS$ ATTRIBUTES Default :: MPI_BCAST
    !MS$ ATTRIBUTES Default :: MPI_COMM_SIZE
    !MS$ ATTRIBUTES Default :: MPI_COMM_RANK
    !MS$ ATTRIBUTES Default :: MPI_GATHERV    
    !MS$ ATTRIBUTES Default :: MPI_INIT 
    !MS$ ATTRIBUTES Default :: MPI_ISEND
    !MS$ ATTRIBUTES Default :: MPI_FINALIZE
    !MS$ ATTRIBUTES Default :: MPI_RECV
    !MS$ ATTRIBUTES Default :: MPI_TYPE_COMMIT
    !MS$ ATTRIBUTES Default :: MPI_TYPE_FREE
    !MS$ ATTRIBUTES Default :: MPI_TYPE_STRUCT
    !MS$ ATTRIBUTES Default :: MPI_WAITALL

	!! !MS$ ATTRIBUTES Default :: MPI_NULL_DELETE_FN
    !! !MS$ ATTRIBUTES Default :: mpi_dup_fn    
    !! !MS$ ATTRIBUTES Default :: mpi_null_delete_fn    
    !! !MS$ ATTRIBUTES Default :: mpi_null_copy_fn    
    !! !MS$ ATTRIBUTES Default :: mpi_comm_dup_fn    
    !! !MS$ ATTRIBUTES Default :: mpi_comm_null_delete_fn
    !! !MS$ ATTRIBUTES Default :: mpi_comm_null_copy_fn
    !! !MS$ ATTRIBUTES Default :: mpi_win_dup_fn
    !! !MS$ ATTRIBUTES Default :: mpi_win_null_delete_fn
    !! !MS$ ATTRIBUTES Default :: mpi_win_null_copy_fn
    !! !MS$ ATTRIBUTES Default :: mpi_type_dup_fn
    !! !MS$ ATTRIBUTES Default :: mpi_type_null_delete_fn
    !! !MS$ ATTRIBUTES Default :: mpi_type_null_copy_fn
    !! !MS$ ATTRIBUTES Default :: mpi_conversion_fn_null 
    !! !MS$ ATTRIBUTES Default :: mpipriv1
    !! !MS$ ATTRIBUTES Default :: mpipriv2
